# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/AvaloniaProgressRing" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Deadpikle"
    target-branch: "main"
    commit-message:
      # Prefix all commit messages
      prefix: "[Dependabot]"
    labels:
      - "dependabot"
      - "awaiting triage"
    reviewers:
      - "Deadpikle"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/AvaloniaProgressRingSample" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Deadpikle"
    target-branch: "main"
    commit-message:
      # Prefix all commit messages
      prefix: "[Dependabot]"
    labels:
      - "dependabot"
      - "awaiting triage"
    reviewers:
      - "Deadpikle"
 