name: publish to nuget
on:
  push:
    branches:
      - master # Your default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.100
      - name: build AvaloniaProgressRing in Release
        run: dotnet build AvaloniaProgressRing/AvaloniaProgressRing.csproj --configuration Release
      
      # Publish
      - name: publish Deadpikle.AvaloniaProgressRing on version change
        uses: rohith/publish-nuget@v2.1.2
        with:
          PROJECT_FILE_PATH: AvaloniaProgressRing/AvaloniaProgressRing.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
          PACKAGE_NAME: Deadpikle.AvaloniaProgressRing
        
     